version: '2'
services:
  postgres:
    image: postgres:10
    restart: unless-stopped
    environment:
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD: metabase
      POSTGRES_USER: metabase
    ports:
      - 54320:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  metabase:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_HOST: postgres
      MB_DB_PORT: 5432
    ports:
      - 3100:3000
    depends_on:
      - postgres
    volumes:
      - metabase:/metabase-data

volumes:
  postgres:
    external: false
  metabase:
    external: false